apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-datacenter
  name: pod-datacenter
spec:
  volumes:
  - name: pvc-datacenter
    persistentVolumeClaim:
      claimName: pvc-datacenter
  containers:
  - image: nginx:latest
    name: container-datacenter 
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: pvc-datacenter
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

