apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-devops
  name: secret-devops
spec:
  volumes:
  - name: media
    secret:
      secretName: media
  containers:
  - image: centos:latest
    name: secret-container-devops
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 300;done"]
    volumeMounts:
    - name: media
      mountPath: /opt/cluster
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
